/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DashboardHome {
    }
    interface PresetManager {
    }
}
declare global {
    interface HTMLDashboardHomeElement extends Components.DashboardHome, HTMLStencilElement {
    }
    var HTMLDashboardHomeElement: {
        prototype: HTMLDashboardHomeElement;
        new (): HTMLDashboardHomeElement;
    };
    interface HTMLPresetManagerElement extends Components.PresetManager, HTMLStencilElement {
    }
    var HTMLPresetManagerElement: {
        prototype: HTMLPresetManagerElement;
        new (): HTMLPresetManagerElement;
    };
    interface HTMLElementTagNameMap {
        "dashboard-home": HTMLDashboardHomeElement;
        "preset-manager": HTMLPresetManagerElement;
    }
}
declare namespace LocalJSX {
    interface DashboardHome {
    }
    interface PresetManager {
    }
    interface IntrinsicElements {
        "dashboard-home": DashboardHome;
        "preset-manager": PresetManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dashboard-home": LocalJSX.DashboardHome & JSXBase.HTMLAttributes<HTMLDashboardHomeElement>;
            "preset-manager": LocalJSX.PresetManager & JSXBase.HTMLAttributes<HTMLPresetManagerElement>;
        }
    }
}
